---
lint:hadolint:
  stage: lint
  image:
    name: megabytelabs/hadolint:slim
    entrypoint: ['']
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
    - exists:
        - Dockerfile
  needs: []
  variables:
    GIT_DEPTH: 1
  script:
    - hadolint Dockerfile
