---
lint:shellcheck:
  stage: lint
  image:
    name: megabytelabs/shellcheck:slim
    entrypoint: ['']
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
    - exists:
        - '**/*.{sh,sh.j2}'
  needs: []
  variables:
    GIT_DEPTH: 1
  script:
    - shellcheck
