---
lint:yamllint:
  stage: lint
  image:
    name: megabytelabs/yamllint:slim
    entrypoint: ['']
  allow_failure: true
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
    - exists:
        - '**/*.{yaml,yml}'
  needs: []
  variables:
    GIT_DEPTH: 1
  script:
    - yamllint -c .config/yamllint.yml .
